language: java
jdk:
    - openjdk8
install:
  - ./setup-env.sh
script: ./gradlew jacocoRootReport --refresh-dependencies --stacktrace
after_success:
    - ./gradlew bintrayUpload
    # - ./gradlew uploadCoverageToCodacy
#    - bash <(curl -s https://codecov.io/bash)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/